version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongodb_container'
    env_file:
      - news_classifier.env
    ports:
      - "27016:27017"
    volumes:
      - mongo-volume:/data/db
    networks:
      - mongodb_nw
  news_classifier:
    build:
      context: .
      dockerfile: 'Dockerfile.flask'
    container_name: 'flask_app_container'
    env_file:
      - news_classifier.env
    volumes:
      - ./packages:/opt/services/news_classifier
    networks:
      - web_nw
      - mongodb_nw
    depends_on: 
      - mongo
  cron:
    build:
      context: .
      dockerfile: 'Dockerfile.cron'
    container_name: cron_container
    networks:
      - mongodb_nw
      - mlflow_nw
    depends_on:
        - mongo
    env_file:
      - news_classifier.env
  mlflow:
    build:
      context: .
      dockerfile: 'Dockerfile.mlflow'
    container_name: mlflow_container
    networks:
      - mlflow_nw
    ports:
      - "5000:5000"
    command: 'mlflow server --backend-store-uri ./mlflow --host 0.0.0.0 --port 5000'
  nginx:
    image: "nginx:1.13.5"
    container_name: 'nginx_container'
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on: 
      - news_classifier
networks:
  web_nw:
    driver: bridge
  mongodb_nw:
    driver: bridge
  mlflow_nw:
    driver: bridge
volumes:
  packages:
  mongo-volume: