version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongodb_container'
    env_file:
      - news_classifier.env
    ports:
      - "27016:27017"
    volumes:
      - mongo-volume:/data/db
    networks:
      - mongodb_nw
  news_classifier:
    build:
      context: .
      dockerfile: 'Dockerfile.flask'
    container_name: 'flask_app_container'
    env_file:
      - news_classifier.env
    volumes:
      - ./packages:/opt/services/news_classifier
    networks:
      - web_nw
      - mongodb_nw
    depends_on: 
      - mongo
  postgres:
      image: postgres:9.6
      container_name: postgres_container
      env_file:
        - news_classifier.env
      networks:
        - postgres_nw
  airflow:                                            
    build:
      context: .
      dockerfile: 'Dockerfile.airflow'
    container_name: airflow_container
    restart: always
    networks:
      - postgres_nw
      - mongodb_nw
    depends_on:
        - postgres
        - mongo
    env_file:
      - news_classifier.env
    volumes:
        - ./dags:/usr/local/airflow/dags
    ports:
        - "8082:8080"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3
  mlflow:
    build:
      context: .
      dockerfile: 'Dockerfile.mlflow'
    container_name: mlflow_container
    ports:
      - "5000:5000"
    command: 'mlflow server --backend-store-uri ./mlflow --host 0.0.0.0 --port 5000'
  nginx:
    image: "nginx:1.13.5"
    container_name: 'nginx_container'
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on: 
      - news_classifier
networks:
  web_nw:
    driver: bridge
  mongodb_nw:
    driver: bridge
  postgres_nw:
    driver: bridge
volumes:
  packages:
  mongo-volume: