version: '3'
services:
  news_classifier:
    build: .
    volumes:
      - ./packages:/opt/services/news_classifier
    networks:
      - web_nw
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on: 
      - news_classifier
networks:
  web_nw:
    driver: bridge
volumes:
  packages: